name: glados
description: "ðŸ° A simple testing framework that tries to break your properties."
version: 0.4.0

repository: https://github.com/marcelgarus/glados

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^1.1.0
  build: ^1.6.3
  characters: ^1.0.0
  meta: ^1.0.0
  source_gen: ^0.9.7
  test: ^1.0.0

dev_dependencies:
  pedantic: ^1.9.0
