name: glados
description: "ðŸ° A property-based testing framework that tries to break your invariances."
version: 0.1.4

repository: https://github.com/marcelgarus/glados

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  analyzer: ^0.40.4
  build: ^1.5.0
  meta: ^1.0.0
  source_gen: ^0.9.7
  test: ^1.0.0
