name: glados
description: "ðŸ° A property-based testing framework that tries to break your invariances."
version: 0.1.3

repository: https://github.com/marcelgarus/glados

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  test: ^1.0.0
  meta: ^1.0.0
