name: glados
description: "ðŸ° A property-based testing framework that tries to break your invariances."
version: 0.0.2

repository: https://github.com/marcelgarus/glados

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  test: ^1.0.0
